package uicp:task_csv_parse@1.2.0;

use uicp:host/system;

interface types {
  record input {
    source: string,
    has_header: bool,
  }
  type output = list<list<string>>;
}

interface task {
  use types.{input, output};
  run: func(job: string, input: input) -> result<output, string>;
}

world entry {
  import system;
  export task;
}

