package uicp:task-table-query@0.1.0;

interface types {
  record filter {
    col: u32,
    needle: string,
  }
  record input {
    rows: list<list<string>>,
    select: list<u32>,
    where_contains: option<filter>,
  }
  type output = list<list<string>>;
}

interface table {
  use types.{filter, input, output};
  enum error { cancelled }
  run: func(job_id: string, input: input) -> result<output, error>;
}

world task {
  import wasi:io/streams@0.2.8;
  import wasi:clocks/monotonic-clock@0.2.0;
  import uicp:host/control@1.0.0;
  export table;
}
