# CI workflow enforces lint, tests, e2e, and build gates.
name: CI

on:
  push:
    branches: ["main", "feature/**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUN_E2E: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: uicp/package-lock.json
      - name: Create .env for tests
        working-directory: uicp
        run: |
          printf "E2E_ORCHESTRATOR=0\n" > .env
          printf "VITE_MOCK_MODE=true\n" >> .env
          printf "USE_DIRECT_CLOUD=0\n" >> .env
          printf "PLANNER_MODEL=deepseek-v3.1:671b\n" >> .env
          printf "ACTOR_MODEL=qwen3-coder:480b\n" >> .env
      - name: Install dependencies
        working-directory: uicp
        run: npm ci
      - name: Lint
        working-directory: uicp
        run: npm run lint
      - name: Typecheck
        working-directory: uicp
        run: npm run typecheck
      - name: Unit tests
        working-directory: uicp
        run: npm run test
      - name: Build
        working-directory: uicp
        run: npm run build
      - name: Install Playwright Browsers
        if: ${{ env.RUN_E2E == 'true' }}
        working-directory: uicp
        run: npx playwright install --with-deps
      - name: E2E tests
        if: ${{ env.RUN_E2E == 'true' }}
        working-directory: uicp
        run: npm run test:e2e
