name: Verify Modules Manifest

on:
  push:
    paths:
      - 'uicp/src-tauri/modules/**'
      - 'uicp/scripts/verify-modules.mjs'
      - 'uicp/package.json'
      - 'uicp/pnpm-lock.yaml'
  pull_request:
    paths:
      - 'uicp/src-tauri/modules/**'
      - 'uicp/scripts/verify-modules.mjs'
      - 'uicp/package.json'
      - 'uicp/pnpm-lock.yaml'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20.19.5'
      - name: Verify modules
        run: |
          node uicp/scripts/verify-modules.mjs --manifest uicp/src-tauri/modules/manifest.json --dir uicp/src-tauri/modules
